name: Train Model on Push

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download windt.csv from Google Drive
      run: |
        FILE_ID=1Sb-QH78ES9GPBOFBEi1h0e7g2nG6xfyv
        curl -L -o data/windt.csv "https://drive.google.com/uc?export=download&id=$FILE_ID"

    - name: Run training script
      run: python src/train.py
